### ISSUE TITLE
Cant opent he Veiwer with V. 3.8.1.9-pre

### ISSUE THREAD

**Issue by Mushmon** [KCV-Localisation/KanColleViewer#75]
I open it and it never opens. tried running as admin as well. My veiwer said new version click to download so I did. heres the log.

===========================================================
ERROR, date = 8/14/2015 8:43:30 PM -05:00, sender = Name:KanColleViewer.exe
There are no context policies.
,
System.ComponentModel.Composition.CompositionException: The composition produced a single composition error. The root cause is provided below. Review the CompositionException.Errors property for more detailed information.

1) Method not found: 'Void Grabacr07.KanColleViewer.ViewModels.Catalogs.ShipCatalogSortWorker.SetTarget(Grabacr07.KanColleViewer.ViewModels.Catalogs.ShipCatalogSortTarget, Boolean)'.

Resulting in: An exception occurred while trying to create an instance of type 'ExperienceCalculator.ExperienceCalculator'.

Resulting in: Cannot activate part 'ExperienceCalculator.ExperienceCalculator'.
Element: ExperienceCalculator.ExperienceCalculator -->  ExperienceCalculator.ExperienceCalculator -->  DirectoryCatalog (Path="C:\Users\***\Downloads\KanColleViewer\Plugins")

Resulting in: Cannot get export 'ExperienceCalculator.ExperienceCalculator (ContractName="Grabacr07.KanColleViewer.Composition.IToolPlugin")' from part 'ExperienceCalculator.ExperienceCalculator'.
Element: ExperienceCalculator.ExperienceCalculator (ContractName="Grabacr07.KanColleViewer.Composition.IToolPlugin") -->  ExperienceCalculator.ExperienceCalculator -->  DirectoryCatalog (Path="C:\Users\****\Downloads\KanColleViewer\Plugins")

   at System.ComponentModel.Composition.Hosting.CompositionServices.GetExportedValueFromComposedPart(ImportEngine engine, ComposablePart part, ExportDefinition definition)
   at System.ComponentModel.Composition.Hosting.CatalogExportProvider.GetExportedValue(CatalogPart part, ExportDefinition export, Boolean isSharedPart)
   at System.ComponentModel.Composition.Hosting.CatalogExportProvider.CatalogExport.GetExportedValueCore()
   at System.ComponentModel.Composition.Primitives.Export.get_Value()
   at System.ComponentModel.Composition.ExportServices.GetCastedExportedValue[T](Export export)
   at System.ComponentModel.Composition.ExportServices.<>c__DisplayClass4`2.<CreateStronglyTypedLazyOfTM>b__1()
   at System.Lazy`1.CreateValue()
   at System.Lazy`1.LazyInitValue()
   at System.Lazy`1.get_Value()
   at Grabacr07.KanColleViewer.ViewModels.Composition.PluginViewModelBase`1..ctor(Lazy`2 plugin)
   at Grabacr07.KanColleViewer.ViewModels.SettingsViewModel.<>c.<ReloadPlugins>b__157_1(Lazy`2 x)
   at System.Linq.Enumerable.WhereSelectArrayIterator`2.MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at Grabacr07.KanColleViewer.ViewModels.SettingsViewModel.ReloadPlugins()
   at Grabacr07.KanColleViewer.ViewModels.SettingsViewModel..ctor()
   at Grabacr07.KanColleViewer.ViewModels.MainWindowViewModel..ctor()
   at Grabacr07.KanColleViewer.App.OnStartup(StartupEventArgs e)
   at System.Windows.Application.<.ctor>b__1(Object unused)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at MS.Internal.Threading.ExceptionFilterHelper.TryCatchWhen(Object source, Delegate method, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.DispatcherOperation.InvokeImpl()
   at System.Windows.Threading.DispatcherOperation.InvokeInSecurityContext(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Windows.Threading.DispatcherOperation.Invoke()
   at System.Windows.Threading.Dispatcher.ProcessQueue()
   at System.Windows.Threading.Dispatcher.WndProcHook(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at MS.Internal.Threading.ExceptionFilterHelper.TryCatchWhen(Object source, Delegate method, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)
   at MS.Win32.UnsafeNativeMethods.DispatchMessage(MSG& msg)
   at System.Windows.Threading.Dispatcher.PushFrameImpl(DispatcherFrame frame)
   at System.Windows.Threading.Dispatcher.PushFrame(DispatcherFrame frame)
   at System.Windows.Threading.Dispatcher.Run()
   at System.Windows.Application.RunDispatcher(Object ignore)
   at System.Windows.Application.RunInternal(Window window)
   at System.Windows.Application.Run(Window window)
   at Grabacr07.KanColleViewer.App.Main()

**Comment by Mushmon** [comment]
Oh removing the Exp counter file seemed to fix it
