### ISSUE TITLE
3.8.1.9-pre Crashes on Load

### ISSUE THREAD

**Issue by Azlodin** [KCV-Localisation/KanColleViewer#76]
I tried resetting all config files and I keep getting the same error within the log. Not sure what's causing it at this point.

===========================================================
ERROR, date = 8/15/2015 8:38:45 AM -04:00, sender = Name:KanColleViewer.exe
There are no context policies.
,
System.NullReferenceException: Object reference not set to an instance of an object.
   at Grabacr07.KanColleWrapper.Master..ctor(kcsapi_start2 start2)
   at Grabacr07.KanColleWrapper.KanColleClient.<>c__DisplayClass36_0.<<Initialieze>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.<ThrowAsync>b__5(Object state)
   at System.Threading.QueueUserWorkItemCallback.WaitCallback_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.QueueUserWorkItemCallback.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading._ThreadPoolWaitCallback.PerformWaitCallback()

**Comment by Yuubari** [comment]
Check if you have any plug-ins besides Counter, Logger and Windows Notifier.

**Comment by Azlodin** [comment]
Hi, I've had some extra time to look into this. started from a fresh config file, and replaced API Key and things seem t be working at the moment. Not sure why performing these same steps previously didn't fix it.
